FROM debian

RUN apt-get update && apt-get install -y socat
RUN apt-get install -y libc6-i386

RUN mkdir /home/pwn
RUN useradd --home=/home/pwn pwn

COPY return_room /home/pwn/
COPY entry.sh /home/pwn/

RUN chown pwn:pwn /home/pwn/return_room

RUN chmod 4755 /home/pwn/return_room
RUN chmod 4755 /home/pwn/entry.sh

EXPOSE 9022
ENTRYPOINT ["/home/pwn/entry.sh"]
