FROM debian

RUN apt-get update && apt-get install -y socat
RUN apt-get install -y libc6-i386

RUN mkdir /home/pwn
RUN useradd --home=/home/pwn pwn

COPY prison_break /home/pwn/
COPY jail.txt /home/pwn/
COPY entry.sh /home/pwn/

RUN chown pwn:pwn /home/pwn/prison_break

RUN chmod 4755 /home/pwn/prison_break
RUN chmod 4755 /home/pwn/entry.sh

EXPOSE 5555
ENTRYPOINT ["/home/pwn/entry.sh"]
